### PR TITLE
Use Doxygen 1.8.11, but make sure a timestamp is shown

### PR DESCRIPTION
**Pull request by jordan-heemskerk**

### CODE REVIEW

**Comment by jordan-heemskerk** [comment]
Closes #104

**Comment by RobertLeahy** [comment]
What does `footer.html` get us?

**Comment by jordan-heemskerk** [comment]
It's a modified version of the default Doxygen footer (generated by `doxygen -w html header.html footer.html stylesheet.css`). The timestamp was removed from the default footer in a recent release of Doxygen, but I want it to show when we generate the docs.

**Comment by RobertLeahy** [comment]
Is this something that we want in the repo proper (meaning it'll be in the documentation generated by anyone who clones), or would it make more sense as a local modification on our docs server?

**Comment by jordan-heemskerk** [comment]
I think it's worth committing for consistency

**Comment by jordan-heemskerk** [comment]
You good with that? @RobertLeahy

**Comment by RobertLeahy** [comment]
Sure.

I don't have strong feelings one way or another, just thought it was worth bringing up.

**Pull request merged**
